"""demo

Revision ID: 1136d70860a5
Revises: 
Create Date: 2020-03-02 22:19:41.121266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1136d70860a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table',
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('monday', sa.String(), nullable=True),
    sa.Column('tuesday', sa.String(), nullable=True),
    sa.Column('wednesday', sa.String(), nullable=True),
    sa.Column('thursday', sa.String(), nullable=True),
    sa.Column('friday', sa.String(), nullable=True),
    sa.Column('saturday', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('time_table', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('time_table')
    # ### end Alembic commands ###
